[package]
name = "simulator"
version = "0.0.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.45", features = ["alloc", "clock", "now", "std"] }
common = { version = "0.0.0", path = "../common" }
log = { version = "0.4.33", features = ["std"] }
sdl2 = "0.38.0"
simplelog = "0.12.2"
time = "0.3.53"
